### PR TITLE
Create raise_issue.md

### PR DESCRIPTION
**Pull request by milansamuel609**
I have created the PR template

Sections I have added :-

1) Description
2) Issue Number
3) Changes Made
4) Type Of Change
5) Screenshots or Videos
6) How Has This Been Tested
7) Checklist
8) Additional Information

Fixes #31

### CODE REVIEW

**Comment by milansamuel609** [comment]
I have done the changes you have asked. I am really sorry and I apologize. The problem occured when I tried to squash the files into 1. I have not tried squad before and tried for the first time and this error happened with me. I am really sorry 😔.

**Comment by Suraj-kumar00** [comment]
That's okay!

This issue is reagarding PULL_REQUEST_TEMPLATE then why you have named it raise_issue? insteas write raise_pull_request.md and you commit also should be this not issue-raiseing okay. please update these and i'll merge it.

image

**Comment by milansamuel609** [comment]
> That's okay!
> 
> This issue is reagarding PULL_REQUEST_TEMPLATE then why you have named it raise_issue? insteas write raise_pull_request.md and you commit also should be this not issue-raiseing okay. please update these and i'll merge it.
> 
> image

I have fixed it. Please kindly check once.

**Review by Suraj-kumar00 — APPROVED** [review]

**Comment by milansamuel609** [comment]
Actually this PR is not counted as contribution in gssoc extended. Please kindly assign this PR to me and please label it as gssoc ext and also add the level.

**Pull request merged**
