### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by milansamuel609**
I have enhanced the file and also added some more sections.

I have done the following changes :-

1) Enhanced the project structure
2) Added need help with the basics section
3) Added project structure section
4) Added additional method of contributing through GitHub desktop section
5) Added good coding practices section
6) Added the help and support section
7) Added the pull request section
8) Added issue report process section

Fixes:[#26 ]
Closes:[#26 ]

image

image

image

image

image

### CODE REVIEW

**Comment by milansamuel609** [comment]
I have enhanced the contributing.md file. Please kindly check it once.

**Comment by Suraj-kumar00** [comment]
> I have enhanced the contributing.md file. Please kindly check it once.

That's call a good README @milansamuel609, Please update these things:
1. Remove the github desktop section.
2. Add this resource for open-source and git & github learning:

opensource blog: https://blog.devsuraj.me/what-is-open-source-beginners-guide-how-to-get-started
git and github: https://blog.devsuraj.me/getting-to-know-git-and-github-your-codes-best-friends

**Comment by milansamuel609** [comment]
> > I have enhanced the contributing.md file. Please kindly check it once.
> 
> That's call a good README @milansamuel609, Please update these things:
> 
> 1. Remove the github desktop section.
> 2. Add this resource for open-source and git & github learning:
> 
> opensource blog: https://blog.devsuraj.me/what-is-open-source-beginners-guide-how-to-get-started git and github: https://blog.devsuraj.me/getting-to-know-git-and-github-your-codes-best-friends

Thank you so much. Also I will do the changes right now !

**Comment by milansamuel609** [comment]
I have enhanced. Please check it once.

**Comment by milansamuel609** [comment]
> Great @milansamuel609, just update your branch please! Do it soon. image

Oh I am really sorry I forget to update. I will do it right now !!

**Comment by milansamuel609** [comment]
Is the file got updated ? Please let me know. Otherwise I will do a new PR for the same issue.

**Comment by Suraj-kumar00** [comment]
Hi @milansamuel609, you just have to first sync your main branch and then update you created branch. You can see here you haven't fetched or pull the 20 commit from the original main branch.
image

Please update that and let me know.

**Comment by milansamuel609** [comment]
I have update it after the sync. Please check it once.

**Comment by milansamuel609** [comment]
> Hi @milansamuel609, you just have to first sync your main branch and then update you created branch. You can see here you haven't fetched or pull the 20 commit from the original main branch. image
> 
> Please update that and let me know.

Thank you for the help 😊

**Review by Suraj-kumar00 — APPROVED** [review]

**Comment by Suraj-kumar00** [comment]
> > Hi @milansamuel609, you just have to first sync your main branch and then update you created branch. You can see here you haven't fetched or pull the 20 commit from the original main branch. image
> > Please update that and let me know.
> 
> Thank you for the help 😊

Happy to help.
Hey @milansamuel609, if you like the project can you please give a star :star: to the repo?

**Comment by milansamuel609** [comment]
> > > Hi @milansamuel609, you just have to first sync your main branch and then update you created branch. You can see here you haven't fetched or pull the 20 commit from the original main branch. image
> > > Please update that and let me know.
> > 
> > 
> > Thank you for the help 😊
> 
> Happy to help. Hey @milansamuel609, if you like the project can you please give a star ⭐ to the repo?

Sure I will 😊. Thank you once again for giving me this opportunity to work on this amazing project 😊

**Comment by Suraj-kumar00** [comment]
> > > > Hi @milansamuel609, you just have to first sync your main branch and then update you created branch. You can see here you haven't fetched or pull the 20 commit from the original main branch. image
> > > > Please update that and let me know.
> > > 
> > > 
> > > Thank you for the help 😊
> > 
> > 
> > Happy to help. Hey @milansamuel609, if you like the project can you please give a star ⭐ to the repo?
> 
> Sure I will 😊. Thank you once again for giving me this opportunity to work on this amazing project 😊

If you want to work on any other issue let me know!

**Comment by milansamuel609** [comment]
> > > > > Hi @milansamuel609, you just have to first sync your main branch and then update you created branch. You can see here you haven't fetched or pull the 20 commit from the original main branch. image
> > > > > Please update that and let me know.
> > > > 
> > > > 
> > > > Thank you for the help 😊
> > > 
> > > 
> > > Happy to help. Hey @milansamuel609, if you like the project can you please give a star ⭐ to the repo?
> > 
> > 
> > Sure I will 😊. Thank you once again for giving me this opportunity to work on this amazing project 😊
> 
> If you want to work on any other issue let me know!

Sure!!!

**Comment by milansamuel609** [comment]
@Suraj-kumar00 Please kindly add the gssoc extend and level label to this PR also. The another one that was PR creation is now marked as accepted.

**Comment by milansamuel609** [comment]
@Suraj-kumar00 Please kindly add the gssoc extend and level label.

**Comment by milansamuel609** [comment]
@Suraj-kumar00 Please attach the gssoc extend and level label also

**Comment by MastanSayyad** [comment]
Hi @Suraj-kumar00 If you are active then please review this PR and add level 1 label + you didnt add me as a collborator yet in your repo, please do that too

**Comment by Suraj-kumar00** [comment]
> Hi @Suraj-kumar00 If you are active then please review this PR and add level 1 label + you didnt add me as a collborator yet in your repo, please do that too

Hi @MastanSayyad, what are you talking about Please link which PR and Why should I add you Collaborator in my repo?

**Comment by milansamuel609** [comment]
@Suraj-kumar00 please add the gssoc extend and level label to this PR.

**Comment by MastanSayyad** [comment]
@Suraj-kumar00, I was referring to this PR as it was open for last 5 days 

And, you should add me as a collaborator to your repository. It is clearly mentioned in your selection emails and the PA guidelines that Program Managers must be added as collaborators. This is necessary for monitoring the repository's activity and, in cases where contributors are spamming, we need to adjust labels and review the leaderboard accordingly.

**Pull request merged**
