### PR TITLE
 issue with herobackground #74 

### PR DESCRIPTION
**Pull request by AE-Hertz**
issue with herobackground #74 

Closes: #74 

@Suraj-kumar00 issue resolved. and added motion animations to it too. 

Preview: 

https://github.com/user-attachments/assets/a6947bd7-dfb2-41ce-8fce-1931b99a8ce4

### CODE REVIEW

**Comment by Suraj-kumar00** [comment]
Where is the preview?

**Comment by AE-Hertz** [comment]
its their reload

**Comment by AE-Hertz** [comment]
let me know if any changes required

**Comment by AE-Hertz** [comment]
@Suraj-kumar00 can you confirm is everything is adequate, asap!

**Review by Suraj-kumar00 — APPROVED** [review]

**Pull request merged**
