### PR TITLE
fix: Make generate flashcard text button color white in dark mode.

### PR DESCRIPTION
**Pull request by zaheer-Khan3260**
fix: Make generate flashcard text button color white in dark mode.

### CODE REVIEW

**Comment by zaheer-Khan3260** [comment]
sorry for the bed commit message it done by accident. Now i raised the pr With proper commit message.

**Comment by zaheer-Khan3260** [comment]
@Suraj-kumar00 fix the issue

**Comment by Suraj-kumar00** [comment]
Can you please show me the preview

**Comment by zaheer-Khan3260** [comment]
sure

**Comment by zaheer-Khan3260** [comment]
Screenshot 2024-10-24 195207
here is the preview.

**Review by Suraj-kumar00 — APPROVED** [review]

**Pull request merged**
