### PR TITLE
Updated Readme with demo video in dark mode

### PR DESCRIPTION
**Pull request by PAVAN507-STAR**
Added the demo video of the website in dark mode. Closes the issue #39

### CODE REVIEW

**Comment by Suraj-kumar00** [comment]
Sorry @PAVAN507-STAR I can't accept this PR as you haven't followed the standard and why have you maid 10 commit?
and you also followed the PR template.

**Comment by PAVAN507-STAR** [comment]
@Suraj-kumar00 sorry can u tell me what changes do i need to do(The 10 commits was due to me changing the video files as the video quality good at first when i tried)

**Comment by PAVAN507-STAR** [comment]
@Suraj-kumar00 can u share the template if u don't mind i can't find it in contribution guidelines

**Comment by Suraj-kumar00** [comment]
> > So you can make change as many times you want @PAVAN507-STAR at your local machine but you have to just commit the changes when it right and final change okay.
> > If you like the project please do consider to give the repo a star 🌟
> 
> Yeah got it.I'm new to opensource .Sorry for the trouble btw

That's okay @PAVAN507-STAR, we are here to help you!

if you want to read blog on open source I have wrote a blog on it you can read it here: blog.devsuraj.me

**Comment by PAVAN507-STAR** [comment]
Hii @Suraj-kumar00  sir.I've raised anther PR now regarding this issue, with only one commit this time .Thanks for the help btw.

**Pull request closed without merging**
