### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AnushkaChouhan25**
Fix Issue -  #7
image

### CODE REVIEW

**Comment by Suraj-kumar00** [comment]
Hi @AnushkaChouhan25, please move the CONTRIBUTING.md file link  below the development area!

**Comment by AnushkaChouhan25** [comment]
> Hi @AnushkaChouhan25, please move the CONTRIBUTING.md file link below the development area!

Done 
image

**Comment by Suraj-kumar00** [comment]
@AnushkaChouhan25, You have already included the contributing guidelines in the development sections, So why you have added it again in the contact section?
image

**Comment by AnushkaChouhan25** [comment]
@Suraj-kumar00 It was already added, I forgot to remove it, I have done it now, and do any other changes need to be made?

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 It was already added, I forgot to remove it, I have done it now, and do any other changes need to be made?

Pardon me I forgot to tell!
What is Jarvis here?

**Comment by AnushkaChouhan25** [comment]
> > @Suraj-kumar00 It was already added, I forgot to remove it, I have done it now, and do any other changes need to be made?
> 
> Pardon me I forgot to tell! What is Jarvis here?

It's done, I changed it 👍

**Comment by AnushkaChouhan25** [comment]
Hi @Suraj-kumar00 
As I told you, I was getting an error while running localhost because of these files. I was not able to make changes in the repo, and this file was showing some changes that I never made. So I discarded the changes, which is why it's showing the file as changed. 
And it will not make any difference to the original site, I have updated only the readme file.

**Comment by AnushkaChouhan25** [comment]
Hi @Suraj-kumar00
As I told you, I was getting an error while running localhost because of these files. I was not able to make changes in the repo, and this file was showing some trailing space in the source. So I discarded it, which is why it's showing the file as changed.

And it will not make any difference to the original site, I have updated only the readme file.
Screenshot 2024-10-15 201748

**Comment by Suraj-kumar00** [comment]
Hey @AnushkaChouhan25, I told you made mistakes those files are deleted. Now I have to push those agian. I didn't expect that.

**Comment by AnushkaChouhan25** [comment]
> Hey @AnushkaChouhan25, I told you made mistakes those files are deleted. Now I have to push those agian. I didn't expect that.

Sorry for that, that was not my intention, I just want to resolve the error. Apologize for this.

**Comment by Suraj-kumar00** [comment]
Hi @AnushkaChouhan25, If you are getting errors on your local machine while setting up the project you should ask for help not just delete the files. Please do remember next time.

**Pull request merged**
