### PR TITLE
Update README with New Badges and Improved Documentation

### PR DESCRIPTION
**Pull request by Ganeshmoorthii**
### Description for Pull Request:
This pull request includes the following updates to the README file:

- Added relevant GitHub badges (stars, forks, issues, pull requests) for better project visibility and quick access to repository stats.
- Improved formatting for better readability and consistency.
- Updated content sections to clarify project goals, installation steps, and contribution guidelines.
- Enhanced the contribution section with detailed steps for new contributors.

## Screenshot
Screenshot 2024-10-20 164332

Please label this PR with:
- `gssoc-ext` for contributions under GirlScript Summer of Code Extended.
- `hacktoberfest-accepted` to ensure it counts towards Hacktoberfest.

Thank you for reviewing my contribution! Let me know if any further changes are required.

### CODE REVIEW

**Comment by Ganeshmoorthii** [comment]
I think Now Its work proper

**Comment by Suraj-kumar00** [comment]
Can you see the dublicasy here?

the star counting i already have but just add the other fours in the above only and just add these labels and don't add the above heading just add these labels in the above only. Let me know if you don't understand anything

image

**Comment by Ganeshmoorthii** [comment]
I can remove the star ⭐

**Comment by Ganeshmoorthii** [comment]
All other ok for you

**Pull request closed without merging**
