### PR TITLE
Update readme

### LINKED ISSUE #15: Create a demo video of the project.
Create complete demo video of how the project works:
- Head over to the landing page.
- Sign-in with gooogle.
- Generate flashcard of any teach topics like `DevOps` `Cloud` `Development` etc...

After the video completes Update it to the `README` file  Below the description and above Build with section like in between them.

The video only include the entering on the landing page and generating and saving the flascard. no more no less.

### PR DESCRIPTION
**Pull request by Shivansh-22866**
Fixes #15 

Check the video below the description, I have signed in, and generated the cards with "DevOps" as input text

### CODE REVIEW

**Comment by Suraj-kumar00** [comment]
> Fixes #15
> 
> Check the video below the description, I have signed in, and generated the cards with "DevOps" as input text

Hi @Shivansh-22866, appreciate you contribution. But can we do something like this like in a flow?
check out this: https://github.com/pratikkumar-mohite/s3-cleaner/blob/master/docs/gif/s3-cleaner-usage.gif

and for now please use light mode because the dark mode is not working properly.

Can you see that its looking very unprofessional. 

the screencast naming, so please do try to do like i provide you the link above. 
And please upload you content in the public folder with proper naming.

image

Hope this will help to improve this. And don't forget to give this repo a star :star2: 

Thanks for you contribution.

**Comment by Shivansh-22866** [comment]
@Suraj-kumar00 I have added a proper gif and the video is taken in light mode. Please check.

**Comment by Shivansh-22866** [comment]
@Suraj-kumar00 I have tried using a higher quality GIF, can you check once again?

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 I have tried using a higher quality GIF, can you check once again?

Do you call this a high quality?
Screenshot from 2024-10-18 17-20-47

**Comment by Shivansh-22866** [comment]
@Suraj-kumar00 extremely sorry sir. I will try to rectify it as soon as possible.
I have one GIF with resolution of 1920 x 900 px. If this is better, then I can add this one instead.
vs9mBkpY37Ae
Again sorry for my mistake

**Comment by Shivansh-22866** [comment]
@Suraj-kumar00 hey
So I tried converting it to Full HD GIF (1920 x 780 px) and this is what I got
Screencast_20241018_113744 (3)

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 hey So I tried converting it to Full HD GIF (1920 x 780 px) and this is what I got Screencast_20241018_113744 (3) [ Screencast_20241018_113744 (3) ](https://private-user-images.githubusercontent.com/131197200/378049184-580d1118-f439-445c-8d92-26a4f887e926.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDAzODEsIm5iZiI6MTcyOTM0MDA4MSwicGF0aCI6Ii8xMzExOTcyMDAvMzc4MDQ5MTg0LTU4MGQxMTE4LWY0MzktNDQ1Yy04ZDkyLTI2YTRmODg3ZTkyNi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMjE0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGUyNTdmYjdmZGJkNWY1NWRmOWNhNjQwOGY3NTUyMWE3MzZkNzUyODkwOWJkNGJlODQ4ZWM5NDUwZTk0NmU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fFBI5jGE-7Kc2wqucEkx-vVdyiwKX0OdQUP0gkSPVqc) [ ](https://private-user-images.githubusercontent.com/131197200/378049184-580d1118-f439-445c-8d92-26a4f887e926.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDAzODEsIm5iZiI6MTcyOTM0MDA4MSwicGF0aCI6Ii8xMzExOTcyMDAvMzc4MDQ5MTg0LTU4MGQxMTE4LWY0MzktNDQ1Yy04ZDkyLTI2YTRmODg3ZTkyNi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMjE0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGUyNTdmYjdmZGJkNWY1NWRmOWNhNjQwOGY3NTUyMWE3MzZkNzUyODkwOWJkNGJlODQ4ZWM5NDUwZTk0NmU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fFBI5jGE-7Kc2wqucEkx-vVdyiwKX0OdQUP0gkSPVqc)

Okay then update this gif in your readme file and update your PR!
For now I think we can just do this better now, But what i was saying is that the spotlights are visible. Anyways update your PR and i'll merge it!

**Comment by Suraj-kumar00** [comment]
Hey @Shivansh-22866 please update your branch and then open again the PR.
image

and in the readme add the image in this way:
`demo`

And please consider to give the repo a star :star: this will help to grow the project.

**Comment by Suraj-kumar00** [comment]
I think now readme is looking good just please update your main and update-readme branches okay: do it soon!
image

**Comment by Shivansh-22866** [comment]
@Suraj-kumar00 both the branches are upto date now

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 both the branches are upto date now

No it's not, you have update your readme-update branch please update soon!
image

And please consider to give the repo a star ⭐ this will help to grow the project.

**Comment by Shivansh-22866** [comment]
I have synced the fork, any changes that were behind in the upstream also got included, no?

**Comment by Suraj-kumar00** [comment]
Hi @Shivansh-22866, everything is okay now but please update you main and update-readme branch because you have updated yet please do asap.

**Comment by Shivansh-22866** [comment]
Yes sir, I have merged the upstream branch for both the branches and verified it

**Comment by Suraj-kumar00** [comment]
> Yes sir, I have merged the upstream branch for both the branches and verified it

Hey @Shivansh-22866 thanks for your contribution it means a lot!

Can you please give a star :star2:  if you like the project so far?

**Pull request merged**
