### PR TITLE
fix navbar User name issue and also fix generate bg 

### PR DESCRIPTION
**Pull request by alok-mishra143**
fix navbar User name issue and also fix generate bg 

https://github.com/user-attachments/assets/46cd2dc7-5e34-4983-9e43-cbccc2bd88ae

### CODE REVIEW

**Comment by alok-mishra143** [comment]
@Suraj-kumar00 fixed the issue that you mention check out and merge it

**Comment by Suraj-kumar00** [comment]
Hey @alok-mishra143, thanks for contribution.

Can you please update your branch?
image

**Comment by Suraj-kumar00** [comment]
> Hey @alok-mishra143, thanks for contribution.
> 
> Can you please update your branch? image

It's okay I resolved the conflict.

**Review by Suraj-kumar00 — APPROVED** [review]
Great Job!

**Pull request merged**
