### PR TITLE
[Documentation]: Creating The PR Template

### PR DESCRIPTION
**Pull request by milansamuel609**
I have created the PR template.

Sections I have added :-

1) Description
2) Issue Number
3) Changes Made
4) Type Of Change
5) Screenshots or Videos
6) How Has This Been Tested
7) Checklist
8) Additional Information

Fixes:[#28 ]
Closes:[#28 ]

image

### CODE REVIEW

**Comment by milansamuel609** [comment]
I have created the PR template. Please kindly check it once.

**Comment by Suraj-kumar00** [comment]
Hi @milansamuel609, that's great!
Can you please squash these  4 commits into 1 so that the standard should be maintained. 
After doing that please update your branch and let me know and i'll review the changes and merge ASAP.

**Comment by Suraj-kumar00** [comment]
And please create a `PULL_REQUEST_TEMPLATE` folder and add this there not in issue_template.

**Comment by milansamuel609** [comment]
> Hi @milansamuel609, that's great! Can you please squash these 4 commits into 1 so that the standard should be maintained. After doing that please update your branch and let me know and i'll review the changes and merge ASAP.

Sure

**Comment by milansamuel609** [comment]
> And please create a `PULL_REQUEST_TEMPLATE` folder and add this there not in issue_template.

Ok I will do this now

**Comment by milansamuel609** [comment]
I will do a pull request again ok something wrong happened :(

**Comment by milansamuel609** [comment]
Actually this PR is not counted as contribution in gssoc extended. Please kindly assign this PR to me and please label it as gssoc ext and also add the level.

**Comment by milansamuel609** [comment]
Please assign me this PR also. Otherwise they will not able to verify

**Pull request closed without merging**
