### PR TITLE
Add subscribe 

### LINKED ISSUE #54: Subsribe to the platform
**Is your feature request related to a problem? Please describe.**
I want to add subscribe component so that the user entering their valid mail ids receive a confirmation mail.

**Describe the solution you'd like**
I will create the frontend component and the API for sending mails.

### PR DESCRIPTION
**Pull request by haseebzaki-07**
## fixes #54 

This PR adds a frontend component along with the backend API for subscribing the platform.

note: Add EMAIL_USER and EMAIL_PASS in the .env file and you are good to go!

Screenshot 2024-10-27 121635
Screenshot 2024-10-27 121702
WhatsApp Image 2024-10-27 at 12 27 51 PM

### CODE REVIEW

**Comment by haseebzaki-07** [comment]
hey @Suraj-kumar00 could you please increase the level of the PR.

**Comment by Suraj-kumar00** [comment]
Hi @haseebzaki-07 okay I'll do that, but can you please add the toast effect when someone subscribe?
Take reference from here: https://ui.shadcn.com/docs/components/toast

**Comment by haseebzaki-07** [comment]
Okay i"ll do it

**Comment by haseebzaki-07** [comment]
hey @Suraj-kumar00 changes done!
Screenshot 2024-10-27 125432

**Comment by Suraj-kumar00** [comment]
Hi @haseebzaki-07 can you confirm that I have to add the email user like my email ID and the password of that email right?

**Review by Suraj-kumar00 — APPROVED** [review]

**Comment by haseebzaki-07** [comment]
@Suraj-kumar00 bro please finalize this PR

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 bro please finalize this PR


Haven't you seen i have asked something to you?

**Comment by Suraj-kumar00** [comment]
And please update your PR branch.

**Comment by haseebzaki-07** [comment]
@Suraj-kumar00 Sorry, I missed that message of yours.
Yeah sure you have to add that email id from which you want the mails to be sent to the users and password will be the email's password.

But for security reasons you can consider using the app passwords that can be generated form my google account security section.

**Comment by haseebzaki-07** [comment]
update the branch @Suraj-kumar00

**Comment by haseebzaki-07** [comment]
@Suraj-kumar00 please finalize this PR

**Comment by haseebzaki-07** [comment]
@Suraj-kumar00 can you please assign me the PR. I had missed reading it in the readme. Please do so.

**Comment by haseebzaki-07** [comment]
.take

**Comment by Suraj-kumar00** [comment]
> .take

this pr is merged can't you see that?
that command only works in issues okay.

**Pull request merged**
