### PR TITLE
Add Spacing in Signup Page: Signup Section 

### PR DESCRIPTION
**Pull request by ansiace**
**Enhanced Sign-up Page Styling**: Added `margin-bottom` and `margin-top` to improve the layout and spacing of the Sign-up page.
- **Responsiveness Improvement**: Ensured responsiveness across different device sizes by adjusting margins to maintain a consistent and user-friendly design.
  
  ### Changes Made
- Applied margin adjustments (`margin-top` and `margin-bottom`) to ensure proper spacing.
- Tested the design on various screen sizes to ensure responsiveness and adaptability for different devices.

### CODE REVIEW

**Comment by ansiace** [comment]
- closes #25

**Comment by Suraj-kumar00** [comment]
can you please follow the PR_TEMPLATE

**Comment by ansiace** [comment]
Hi @Suraj-kumar00 
please merge this

**Comment by Suraj-kumar00** [comment]
Please update the branch and show the preview

**Pull request closed without merging**
