### PR TITLE
fix: Choos plan button text is not visible in the dark mode

### PR DESCRIPTION
**Pull request by zaheer-Khan3260**
fix: Choos plan button text is not visible in the dark mode

### CODE REVIEW

**Comment by zaheer-Khan3260** [comment]
here is the screenshot.
Screenshot 2024-10-27 131818

**Comment by zaheer-Khan3260** [comment]
@Suraj-kumar00  merge this pull request.

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 merge this pull request.

Star this repository 🌟

**Comment by Suraj-kumar00** [comment]
Hey @zaheer-Khan3260 isn't it will look good if you set the color also to these two buttons as first one and only the hover effect you can set it to good looking  color same as the theme. And yeah please share the preview.

**Comment by zaheer-Khan3260** [comment]
@Suraj-kumar00 I fix the #53 . I'll open a pull request in that pull request i implement this also. is it sound good?

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 I fix the #53 . I'll open a pull request in that pull request i implement this also. is it sound good?

I have suggested you the changes above.
Please fo that and show me the preview.

And if you like the project please do consider to give the repo a star 🌟

**Comment by zaheer-Khan3260** [comment]
@Suraj-kumar00 yeah i add the color based on the theme and add hover effect also here is the preview.
before hover: 
Screenshot 2024-10-27 142315

after hover: 
Screenshot 2024-10-27 142327

i also the issue #53  i share that preview also look at it.

Dark mode: 
Screenshot 2024-10-27 142559

light mode: 
Screenshot 2024-10-27 142628

**Review by Suraj-kumar00 — APPROVED** [review]

**Comment by Suraj-kumar00** [comment]
Hi @zaheer-Khan3260 thanks for the contribution, and please don't forget to give the repo a star :star2:

**Comment by Suraj-kumar00** [comment]
Hi @zaheer-Khan3260, can you star the repo ?

**Pull request merged**
